name: Deploy to GitHub Pages (11ty)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [content-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true  # Important: This fetches LFS files
          submodules: recursive  # Fetch content submodule

      - name: Update content submodule to latest
        run: |
          git submodule update --init --recursive
          cd content
          git fetch origin main
          git checkout origin/main
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add content
            git commit -m "Update content submodule to latest"
          fi

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build with Eleventy
        run: npm run build
        env:
          NODE_ENV: production
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v4
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
